-- HustleClub baseline migration
-- Safe to run in Supabase SQL Editor.
-- Idempotent where possible.

begin;

create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin(user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = user_id
      and p.role = 'admin'
  );
$$;

revoke all on function public.is_admin(uuid) from public;
grant execute on function public.is_admin(uuid) to anon, authenticated, service_role;

create or replace function public.sync_jobs_owner_columns()
returns trigger
language plpgsql
as $$
begin
  if new.creator_id is null and new.created_by is null then
    new.creator_id := auth.uid();
    new.created_by := auth.uid();
  elsif new.creator_id is null then
    new.creator_id := new.created_by;
  elsif new.created_by is null then
    new.created_by := new.creator_id;
  end if;

  return new;
end;
$$;

create or replace function public.sync_marketplace_owner_columns()
returns trigger
language plpgsql
as $$
begin
  if new.seller_id is null and new.user_id is null then
    new.seller_id := auth.uid();
    new.user_id := auth.uid();
  elsif new.seller_id is null then
    new.seller_id := new.user_id;
  elsif new.user_id is null then
    new.user_id := new.seller_id;
  end if;

  return new;
end;
$$;

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'user')
  on conflict (id) do update
    set email = excluded.email;

  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Tables (create + align columns)
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  full_name text,
  bio text,
  avatar_url text,
  role text not null default 'user',
  email text,
  is_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists role text default 'user';
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists is_verified boolean not null default false;
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.creator_requests (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  message text,
  reason text,
  created_at timestamptz not null default now(),
  decided_at timestamptz
);

alter table public.creator_requests add column if not exists user_id uuid;
alter table public.creator_requests add column if not exists status text not null default 'pending';
alter table public.creator_requests add column if not exists message text;
alter table public.creator_requests add column if not exists reason text;
alter table public.creator_requests add column if not exists created_at timestamptz not null default now();
alter table public.creator_requests add column if not exists decided_at timestamptz;

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text,
  instructor text,
  image_url text,
  status text not null default 'draft',
  price numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.courses add column if not exists creator_id uuid;
alter table public.courses add column if not exists title text;
alter table public.courses add column if not exists description text;
alter table public.courses add column if not exists instructor text;
alter table public.courses add column if not exists image_url text;
alter table public.courses add column if not exists status text not null default 'draft';
alter table public.courses add column if not exists price numeric(12,2) not null default 0;
alter table public.courses add column if not exists created_at timestamptz not null default now();
alter table public.courses add column if not exists updated_at timestamptz not null default now();

create table if not exists public.course_enrollments (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.course_enrollments add column if not exists course_id bigint;
alter table public.course_enrollments add column if not exists user_id uuid;
alter table public.course_enrollments add column if not exists created_at timestamptz not null default now();

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  budget numeric(12,2),
  type text,
  is_open boolean not null default true,
  views integer not null default 0,
  creator_id uuid,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.jobs add column if not exists title text;
alter table public.jobs add column if not exists description text;
alter table public.jobs add column if not exists budget numeric(12,2);
alter table public.jobs add column if not exists type text;
alter table public.jobs add column if not exists is_open boolean not null default true;
alter table public.jobs add column if not exists views integer not null default 0;
alter table public.jobs add column if not exists creator_id uuid;
alter table public.jobs add column if not exists created_by uuid;
alter table public.jobs add column if not exists created_at timestamptz not null default now();
alter table public.jobs add column if not exists updated_at timestamptz not null default now();

create table if not exists public.job_applications (
  id uuid primary key default extensions.gen_random_uuid(),
  job_id bigint not null references public.jobs(id) on delete cascade,
  applicant_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.job_applications add column if not exists job_id bigint;
alter table public.job_applications add column if not exists applicant_id uuid;
alter table public.job_applications add column if not exists status text not null default 'pending';
alter table public.job_applications add column if not exists created_at timestamptz not null default now();

create table if not exists public.job_views (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  viewed_at timestamptz not null default now()
);

alter table public.job_views add column if not exists job_id bigint;
alter table public.job_views add column if not exists user_id uuid;
alter table public.job_views add column if not exists viewed_at timestamptz not null default now();

create table if not exists public.job_ip_views (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  ip_address text not null,
  country text,
  viewed_at timestamptz not null default now()
);

alter table public.job_ip_views add column if not exists job_id bigint;
alter table public.job_ip_views add column if not exists ip_address text;
alter table public.job_ip_views add column if not exists country text;
alter table public.job_ip_views add column if not exists viewed_at timestamptz not null default now();

create table if not exists public.marketplace_items (
  id uuid primary key default extensions.gen_random_uuid(),
  title text not null,
  description text,
  price numeric(12,2) not null default 0,
  image_url text,
  seller_id uuid,
  user_id uuid,
  is_published boolean not null default false,
  is_sold boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.marketplace_items add column if not exists title text;
alter table public.marketplace_items add column if not exists description text;
alter table public.marketplace_items add column if not exists price numeric(12,2) not null default 0;
alter table public.marketplace_items add column if not exists image_url text;
alter table public.marketplace_items add column if not exists seller_id uuid;
alter table public.marketplace_items add column if not exists user_id uuid;
alter table public.marketplace_items add column if not exists is_published boolean not null default false;
alter table public.marketplace_items add column if not exists is_sold boolean not null default false;
alter table public.marketplace_items add column if not exists created_at timestamptz not null default now();
alter table public.marketplace_items add column if not exists updated_at timestamptz not null default now();

create table if not exists public.marketplace_orders (
  id uuid primary key default extensions.gen_random_uuid(),
  item_id uuid not null references public.marketplace_items(id) on delete cascade,
  buyer_id uuid not null references public.profiles(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  price numeric(12,2) not null,
  status text not null default 'paid',
  created_at timestamptz not null default now(),
  shipped_at timestamptz,
  delivered_at timestamptz
);

alter table public.marketplace_orders add column if not exists item_id uuid;
alter table public.marketplace_orders add column if not exists buyer_id uuid;
alter table public.marketplace_orders add column if not exists seller_id uuid;
alter table public.marketplace_orders add column if not exists price numeric(12,2);
alter table public.marketplace_orders add column if not exists status text not null default 'paid';
alter table public.marketplace_orders add column if not exists created_at timestamptz not null default now();
alter table public.marketplace_orders add column if not exists shipped_at timestamptz;
alter table public.marketplace_orders add column if not exists delivered_at timestamptz;

create table if not exists public.audit_logs (
  id uuid primary key default extensions.gen_random_uuid(),
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

alter table public.audit_logs add column if not exists actor_id uuid;
alter table public.audit_logs add column if not exists action text;
alter table public.audit_logs add column if not exists target_type text;
alter table public.audit_logs add column if not exists target_id text;
alter table public.audit_logs add column if not exists metadata jsonb;
alter table public.audit_logs add column if not exists created_at timestamptz not null default now();

create table if not exists public.admin_audit_logs (
  id uuid primary key default extensions.gen_random_uuid(),
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_logs add column if not exists actor_id uuid;
alter table public.admin_audit_logs add column if not exists action text;
alter table public.admin_audit_logs add column if not exists target_type text;
alter table public.admin_audit_logs add column if not exists target_id text;
alter table public.admin_audit_logs add column if not exists metadata jsonb;
alter table public.admin_audit_logs add column if not exists created_at timestamptz not null default now();

create table if not exists public.listings (
  id uuid primary key default extensions.gen_random_uuid(),
  title text not null,
  price numeric(12,2),
  created_at timestamptz not null default now()
);

alter table public.listings add column if not exists title text;
alter table public.listings add column if not exists price numeric(12,2);
alter table public.listings add column if not exists created_at timestamptz not null default now();

-- ---------------------------------------------------------------------------
-- Data alignment
-- ---------------------------------------------------------------------------

update public.jobs
set creator_id = coalesce(creator_id, created_by),
    created_by = coalesce(created_by, creator_id)
where creator_id is null
   or created_by is null;

update public.marketplace_items
set seller_id = coalesce(seller_id, user_id),
    user_id = coalesce(user_id, seller_id)
where seller_id is null
   or user_id is null;

update public.profiles p
set email = u.email
from auth.users u
where u.id = p.id
  and (p.email is null or p.email = '');

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

drop trigger if exists trg_profiles_set_updated_at on public.profiles;
create trigger trg_profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_courses_set_updated_at on public.courses;
create trigger trg_courses_set_updated_at
before update on public.courses
for each row execute function public.set_updated_at();

drop trigger if exists trg_jobs_set_updated_at on public.jobs;
create trigger trg_jobs_set_updated_at
before update on public.jobs
for each row execute function public.set_updated_at();

drop trigger if exists trg_marketplace_items_set_updated_at on public.marketplace_items;
create trigger trg_marketplace_items_set_updated_at
before update on public.marketplace_items
for each row execute function public.set_updated_at();

drop trigger if exists trg_jobs_sync_owner on public.jobs;
create trigger trg_jobs_sync_owner
before insert or update of creator_id, created_by on public.jobs
for each row execute function public.sync_jobs_owner_columns();

drop trigger if exists trg_marketplace_items_sync_owner on public.marketplace_items;
create trigger trg_marketplace_items_sync_owner
before insert or update of seller_id, user_id on public.marketplace_items
for each row execute function public.sync_marketplace_owner_columns();

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'on_auth_user_created_hustleclub'
  ) then
    create trigger on_auth_user_created_hustleclub
    after insert on auth.users
    for each row execute function public.handle_new_user_profile();
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_created_at_idx on public.profiles(created_at desc);

do $$
begin
  begin
    create unique index if not exists profiles_username_unique_idx
      on public.profiles(username)
      where username is not null;
  exception when others then
    raise notice 'profiles_username_unique_idx was skipped: %', sqlerrm;
  end;
end
$$;

create index if not exists creator_requests_user_id_idx on public.creator_requests(user_id);
create index if not exists creator_requests_status_idx on public.creator_requests(status);
create index if not exists creator_requests_created_at_idx on public.creator_requests(created_at desc);

do $$
begin
  begin
    create unique index if not exists creator_requests_pending_unique_idx
      on public.creator_requests(user_id)
      where status = 'pending';
  exception when others then
    raise notice 'creator_requests_pending_unique_idx was skipped: %', sqlerrm;
  end;
end
$$;

create index if not exists courses_creator_id_idx on public.courses(creator_id);
create index if not exists courses_status_idx on public.courses(status);
create index if not exists courses_created_at_idx on public.courses(created_at desc);

create index if not exists course_enrollments_course_id_idx on public.course_enrollments(course_id);
create index if not exists course_enrollments_user_id_idx on public.course_enrollments(user_id);

do $$
begin
  begin
    create unique index if not exists course_enrollments_unique_idx
      on public.course_enrollments(course_id, user_id);
  exception when others then
    raise notice 'course_enrollments_unique_idx was skipped: %', sqlerrm;
  end;
end
$$;

create index if not exists jobs_creator_id_idx on public.jobs(creator_id);
create index if not exists jobs_created_by_idx on public.jobs(created_by);
create index if not exists jobs_is_open_idx on public.jobs(is_open);
create index if not exists jobs_created_at_idx on public.jobs(created_at desc);

create index if not exists job_applications_job_id_idx on public.job_applications(job_id);
create index if not exists job_applications_applicant_id_idx on public.job_applications(applicant_id);
create index if not exists job_applications_status_idx on public.job_applications(status);
create index if not exists job_applications_created_at_idx on public.job_applications(created_at desc);

do $$
begin
  begin
    create unique index if not exists job_applications_unique_idx
      on public.job_applications(job_id, applicant_id);
  exception when others then
    raise notice 'job_applications_unique_idx was skipped: %', sqlerrm;
  end;
end
$$;

create index if not exists job_views_job_id_idx on public.job_views(job_id);
create index if not exists job_views_user_id_idx on public.job_views(user_id);
create index if not exists job_views_viewed_at_idx on public.job_views(viewed_at desc);

do $$
begin
  begin
    create unique index if not exists job_views_unique_idx
      on public.job_views(job_id, user_id);
  exception when others then
    raise notice 'job_views_unique_idx was skipped: %', sqlerrm;
  end;
end
$$;

create index if not exists job_ip_views_job_id_idx on public.job_ip_views(job_id);
create index if not exists job_ip_views_ip_idx on public.job_ip_views(ip_address);
create index if not exists job_ip_views_country_idx on public.job_ip_views(country);
create index if not exists job_ip_views_viewed_at_idx on public.job_ip_views(viewed_at desc);

do $$
begin
  begin
    create unique index if not exists job_ip_views_unique_idx
      on public.job_ip_views(job_id, ip_address);
  exception when others then
    raise notice 'job_ip_views_unique_idx was skipped: %', sqlerrm;
  end;
end
$$;

create index if not exists marketplace_items_seller_id_idx on public.marketplace_items(seller_id);
create index if not exists marketplace_items_user_id_idx on public.marketplace_items(user_id);
create index if not exists marketplace_items_published_idx on public.marketplace_items(is_published);
create index if not exists marketplace_items_sold_idx on public.marketplace_items(is_sold);
create index if not exists marketplace_items_created_at_idx on public.marketplace_items(created_at desc);

create index if not exists marketplace_orders_item_id_idx on public.marketplace_orders(item_id);
create index if not exists marketplace_orders_buyer_id_idx on public.marketplace_orders(buyer_id);
create index if not exists marketplace_orders_seller_id_idx on public.marketplace_orders(seller_id);
create index if not exists marketplace_orders_status_idx on public.marketplace_orders(status);
create index if not exists marketplace_orders_created_at_idx on public.marketplace_orders(created_at desc);

create index if not exists audit_logs_actor_id_idx on public.audit_logs(actor_id);
create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
create index if not exists admin_audit_logs_actor_id_idx on public.admin_audit_logs(actor_id);
create index if not exists admin_audit_logs_created_at_idx on public.admin_audit_logs(created_at desc);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.creator_requests enable row level security;
alter table public.courses enable row level security;
alter table public.course_enrollments enable row level security;
alter table public.jobs enable row level security;
alter table public.job_applications enable row level security;
alter table public.job_views enable row level security;
alter table public.job_ip_views enable row level security;
alter table public.marketplace_items enable row level security;
alter table public.marketplace_orders enable row level security;
alter table public.audit_logs enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.listings enable row level security;

-- profiles
drop policy if exists profiles_select_all on public.profiles;
create policy profiles_select_all
on public.profiles
for select
using (true);

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists profiles_update_self_or_admin on public.profiles;
create policy profiles_update_self_or_admin
on public.profiles
for update
using (auth.uid() = id or public.is_admin(auth.uid()))
with check (auth.uid() = id or public.is_admin(auth.uid()));

drop policy if exists profiles_delete_admin on public.profiles;
create policy profiles_delete_admin
on public.profiles
for delete
using (public.is_admin(auth.uid()));

-- creator_requests
drop policy if exists creator_requests_select_owner_or_admin on public.creator_requests;
create policy creator_requests_select_owner_or_admin
on public.creator_requests
for select
using (auth.uid() = user_id or public.is_admin(auth.uid()));

drop policy if exists creator_requests_insert_owner on public.creator_requests;
create policy creator_requests_insert_owner
on public.creator_requests
for insert
with check (auth.uid() = user_id);

drop policy if exists creator_requests_update_admin on public.creator_requests;
create policy creator_requests_update_admin
on public.creator_requests
for update
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists creator_requests_delete_admin on public.creator_requests;
create policy creator_requests_delete_admin
on public.creator_requests
for delete
using (public.is_admin(auth.uid()));

-- courses
drop policy if exists courses_select_published_or_owner_or_admin on public.courses;
create policy courses_select_published_or_owner_or_admin
on public.courses
for select
using (
  status = 'published'
  or creator_id = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists courses_insert_owner_or_admin on public.courses;
create policy courses_insert_owner_or_admin
on public.courses
for insert
with check (
  creator_id = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists courses_update_owner_or_admin on public.courses;
create policy courses_update_owner_or_admin
on public.courses
for update
using (creator_id = auth.uid() or public.is_admin(auth.uid()))
with check (creator_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists courses_delete_owner_or_admin on public.courses;
create policy courses_delete_owner_or_admin
on public.courses
for delete
using (creator_id = auth.uid() or public.is_admin(auth.uid()));

-- course_enrollments
drop policy if exists course_enrollments_select_scope on public.course_enrollments;
create policy course_enrollments_select_scope
on public.course_enrollments
for select
using (
  user_id = auth.uid()
  or public.is_admin(auth.uid())
  or exists (
    select 1
    from public.courses c
    where c.id = course_enrollments.course_id
      and c.creator_id = auth.uid()
  )
);

drop policy if exists course_enrollments_insert_self on public.course_enrollments;
create policy course_enrollments_insert_self
on public.course_enrollments
for insert
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.courses c
    where c.id = course_enrollments.course_id
      and c.status = 'published'
  )
);

drop policy if exists course_enrollments_delete_self_or_admin on public.course_enrollments;
create policy course_enrollments_delete_self_or_admin
on public.course_enrollments
for delete
using (user_id = auth.uid() or public.is_admin(auth.uid()));

-- jobs
drop policy if exists jobs_select_open_or_owner_or_admin on public.jobs;
create policy jobs_select_open_or_owner_or_admin
on public.jobs
for select
using (
  is_open = true
  or coalesce(creator_id, created_by) = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists jobs_insert_owner_or_admin on public.jobs;
create policy jobs_insert_owner_or_admin
on public.jobs
for insert
with check (
  coalesce(creator_id, created_by) = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists jobs_update_owner_or_admin on public.jobs;
create policy jobs_update_owner_or_admin
on public.jobs
for update
using (
  coalesce(creator_id, created_by) = auth.uid()
  or public.is_admin(auth.uid())
)
with check (
  coalesce(creator_id, created_by) = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists jobs_delete_owner_or_admin on public.jobs;
create policy jobs_delete_owner_or_admin
on public.jobs
for delete
using (
  coalesce(creator_id, created_by) = auth.uid()
  or public.is_admin(auth.uid())
);

-- job_applications
drop policy if exists job_applications_select_scope on public.job_applications;
create policy job_applications_select_scope
on public.job_applications
for select
using (
  applicant_id = auth.uid()
  or public.is_admin(auth.uid())
  or exists (
    select 1
    from public.jobs j
    where j.id = job_applications.job_id
      and coalesce(j.creator_id, j.created_by) = auth.uid()
  )
);

drop policy if exists job_applications_insert_self on public.job_applications;
create policy job_applications_insert_self
on public.job_applications
for insert
with check (
  applicant_id = auth.uid()
  and exists (
    select 1
    from public.jobs j
    where j.id = job_applications.job_id
      and j.is_open = true
  )
);

drop policy if exists job_applications_update_owner_or_admin on public.job_applications;
create policy job_applications_update_owner_or_admin
on public.job_applications
for update
using (
  public.is_admin(auth.uid())
  or exists (
    select 1
    from public.jobs j
    where j.id = job_applications.job_id
      and coalesce(j.creator_id, j.created_by) = auth.uid()
  )
)
with check (
  public.is_admin(auth.uid())
  or exists (
    select 1
    from public.jobs j
    where j.id = job_applications.job_id
      and coalesce(j.creator_id, j.created_by) = auth.uid()
  )
);

drop policy if exists job_applications_delete_scope on public.job_applications;
create policy job_applications_delete_scope
on public.job_applications
for delete
using (
  applicant_id = auth.uid()
  or public.is_admin(auth.uid())
  or exists (
    select 1
    from public.jobs j
    where j.id = job_applications.job_id
      and coalesce(j.creator_id, j.created_by) = auth.uid()
  )
);

-- job_views
drop policy if exists job_views_select_scope on public.job_views;
create policy job_views_select_scope
on public.job_views
for select
using (
  user_id = auth.uid()
  or public.is_admin(auth.uid())
  or exists (
    select 1
    from public.jobs j
    where j.id = job_views.job_id
      and coalesce(j.creator_id, j.created_by) = auth.uid()
  )
);

drop policy if exists job_views_insert_self on public.job_views;
create policy job_views_insert_self
on public.job_views
for insert
with check (user_id = auth.uid());

drop policy if exists job_views_delete_admin on public.job_views;
create policy job_views_delete_admin
on public.job_views
for delete
using (public.is_admin(auth.uid()));

-- job_ip_views
drop policy if exists job_ip_views_select_scope on public.job_ip_views;
create policy job_ip_views_select_scope
on public.job_ip_views
for select
using (
  public.is_admin(auth.uid())
  or exists (
    select 1
    from public.jobs j
    where j.id = job_ip_views.job_id
      and coalesce(j.creator_id, j.created_by) = auth.uid()
  )
);

drop policy if exists job_ip_views_insert_any on public.job_ip_views;
create policy job_ip_views_insert_any
on public.job_ip_views
for insert
with check (true);

drop policy if exists job_ip_views_delete_admin on public.job_ip_views;
create policy job_ip_views_delete_admin
on public.job_ip_views
for delete
using (public.is_admin(auth.uid()));

-- marketplace_items
drop policy if exists marketplace_items_select_scope on public.marketplace_items;
create policy marketplace_items_select_scope
on public.marketplace_items
for select
using (
  (is_published = true and is_sold = false)
  or coalesce(seller_id, user_id) = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists marketplace_items_insert_owner_or_admin on public.marketplace_items;
create policy marketplace_items_insert_owner_or_admin
on public.marketplace_items
for insert
with check (
  coalesce(seller_id, user_id) = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists marketplace_items_update_owner_or_admin on public.marketplace_items;
create policy marketplace_items_update_owner_or_admin
on public.marketplace_items
for update
using (
  coalesce(seller_id, user_id) = auth.uid()
  or public.is_admin(auth.uid())
)
with check (
  coalesce(seller_id, user_id) = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists marketplace_items_delete_owner_or_admin on public.marketplace_items;
create policy marketplace_items_delete_owner_or_admin
on public.marketplace_items
for delete
using (
  coalesce(seller_id, user_id) = auth.uid()
  or public.is_admin(auth.uid())
);

-- marketplace_orders
drop policy if exists marketplace_orders_select_scope on public.marketplace_orders;
create policy marketplace_orders_select_scope
on public.marketplace_orders
for select
using (
  buyer_id = auth.uid()
  or seller_id = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists marketplace_orders_insert_buyer_self on public.marketplace_orders;
create policy marketplace_orders_insert_buyer_self
on public.marketplace_orders
for insert
with check (
  buyer_id = auth.uid()
  and buyer_id <> seller_id
);

drop policy if exists marketplace_orders_update_scope on public.marketplace_orders;
create policy marketplace_orders_update_scope
on public.marketplace_orders
for update
using (
  buyer_id = auth.uid()
  or seller_id = auth.uid()
  or public.is_admin(auth.uid())
)
with check (
  buyer_id = auth.uid()
  or seller_id = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists marketplace_orders_delete_admin on public.marketplace_orders;
create policy marketplace_orders_delete_admin
on public.marketplace_orders
for delete
using (public.is_admin(auth.uid()));

-- audit_logs
drop policy if exists audit_logs_select_admin on public.audit_logs;
create policy audit_logs_select_admin
on public.audit_logs
for select
using (public.is_admin(auth.uid()));

drop policy if exists audit_logs_insert_authenticated on public.audit_logs;
create policy audit_logs_insert_authenticated
on public.audit_logs
for insert
with check (auth.role() = 'authenticated');

-- admin_audit_logs
drop policy if exists admin_audit_logs_select_admin on public.admin_audit_logs;
create policy admin_audit_logs_select_admin
on public.admin_audit_logs
for select
using (public.is_admin(auth.uid()));

drop policy if exists admin_audit_logs_insert_admin on public.admin_audit_logs;
create policy admin_audit_logs_insert_admin
on public.admin_audit_logs
for insert
with check (public.is_admin(auth.uid()));

-- listings
drop policy if exists listings_select_admin on public.listings;
create policy listings_select_admin
on public.listings
for select
using (public.is_admin(auth.uid()));

drop policy if exists listings_insert_admin on public.listings;
create policy listings_insert_admin
on public.listings
for insert
with check (public.is_admin(auth.uid()));

drop policy if exists listings_update_admin on public.listings;
create policy listings_update_admin
on public.listings
for update
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists listings_delete_admin on public.listings;
create policy listings_delete_admin
on public.listings
for delete
using (public.is_admin(auth.uid()));

-- ---------------------------------------------------------------------------
-- Storage buckets + policies
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('marketplace', 'marketplace', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('courses', 'courses', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists avatars_public_read on storage.objects;
create policy avatars_public_read
on storage.objects
for select
using (bucket_id = 'avatars');

drop policy if exists avatars_insert_own_folder on storage.objects;
create policy avatars_insert_own_folder
on storage.objects
for insert
with check (
  bucket_id = 'avatars'
  and auth.role() = 'authenticated'
  and split_part(name, '/', 1) = auth.uid()::text
);

drop policy if exists avatars_update_own_folder on storage.objects;
create policy avatars_update_own_folder
on storage.objects
for update
using (
  bucket_id = 'avatars'
  and auth.role() = 'authenticated'
  and split_part(name, '/', 1) = auth.uid()::text
)
with check (
  bucket_id = 'avatars'
  and auth.role() = 'authenticated'
  and split_part(name, '/', 1) = auth.uid()::text
);

drop policy if exists avatars_delete_own_folder on storage.objects;
create policy avatars_delete_own_folder
on storage.objects
for delete
using (
  bucket_id = 'avatars'
  and auth.role() = 'authenticated'
  and split_part(name, '/', 1) = auth.uid()::text
);

drop policy if exists marketplace_public_read on storage.objects;
create policy marketplace_public_read
on storage.objects
for select
using (bucket_id = 'marketplace');

drop policy if exists marketplace_insert_authenticated on storage.objects;
create policy marketplace_insert_authenticated
on storage.objects
for insert
with check (
  bucket_id = 'marketplace'
  and auth.role() = 'authenticated'
);

drop policy if exists marketplace_update_authenticated on storage.objects;
create policy marketplace_update_authenticated
on storage.objects
for update
using (
  bucket_id = 'marketplace'
  and auth.role() = 'authenticated'
)
with check (
  bucket_id = 'marketplace'
  and auth.role() = 'authenticated'
);

drop policy if exists marketplace_delete_authenticated on storage.objects;
create policy marketplace_delete_authenticated
on storage.objects
for delete
using (
  bucket_id = 'marketplace'
  and auth.role() = 'authenticated'
);

drop policy if exists courses_public_read on storage.objects;
create policy courses_public_read
on storage.objects
for select
using (bucket_id = 'courses');

drop policy if exists courses_insert_authenticated on storage.objects;
create policy courses_insert_authenticated
on storage.objects
for insert
with check (
  bucket_id = 'courses'
  and auth.role() = 'authenticated'
);

drop policy if exists courses_update_authenticated on storage.objects;
create policy courses_update_authenticated
on storage.objects
for update
using (
  bucket_id = 'courses'
  and auth.role() = 'authenticated'
)
with check (
  bucket_id = 'courses'
  and auth.role() = 'authenticated'
);

drop policy if exists courses_delete_authenticated on storage.objects;
create policy courses_delete_authenticated
on storage.objects
for delete
using (
  bucket_id = 'courses'
  and auth.role() = 'authenticated'
);

commit;
